language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - npm test
  - npm run hook
  - npm run test-console
  - npm run test-nested
  - npm run test-symbols
  - npm run test-array
  - npm run test-chain
  - npm run test-compose
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
